print("=============================================")
print("========== Program Rumus Lingkaran ==========")
print("Masukan jari-jari lingkaran (cm) : 4 ")
print("Keliling Lingkaran Adalah = 25.12 cm")
print("Diameter Lingkaran Adalah = 8.0 cm")
print("Luas Lingkaran adalah = 50.24 cm2")